"""create_facts_tables

Revision ID: 2d9490624fda
Revises: 94a0713b6ccc
Create Date: 2026-06-09 00:19:18.140659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2d9490624fda'
down_revision: Union[str, Sequence[str], None] = '94a0713b6ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hard_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('source_agent', sa.String(length=100), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hard_facts'))
    )
    op.create_index(op.f('ix_hard_facts_family_id'), 'hard_facts', ['family_id'], unique=False)
    op.create_index(op.f('ix_hard_facts_user_id'), 'hard_facts', ['user_id'], unique=False)
    op.create_table('soft_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('source_agent', sa.String(length=100), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soft_facts'))
    )
    op.create_index(op.f('ix_soft_facts_family_id'), 'soft_facts', ['family_id'], unique=False)
    op.create_index(op.f('ix_soft_facts_user_id'), 'soft_facts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soft_facts_user_id'), table_name='soft_facts')
    op.drop_index(op.f('ix_soft_facts_family_id'), table_name='soft_facts')
    op.drop_table('soft_facts')
    op.drop_index(op.f('ix_hard_facts_user_id'), table_name='hard_facts')
    op.drop_index(op.f('ix_hard_facts_family_id'), table_name='hard_facts')
    op.drop_table('hard_facts')
    # ### end Alembic commands ###
