"""create context table

Revision ID: 94a0713b6ccc
Revises: 6fa2e97bcb93
Create Date: 2026-06-07 22:25:26.785293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a0713b6ccc'
down_revision: Union[str, Sequence[str], None] = '6fa2e97bcb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contexts'))
    )
    op.create_index(op.f('ix_contexts_session_id'), 'contexts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contexts_session_id'), table_name='contexts')
    op.drop_table('contexts')
    # ### end Alembic commands ###
